---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kbld.k14s.io/images: |
      - origins:
        - resolved:
            tag: latest
            url: danielhelfand/go-web-server:latest
        - preresolved:
            url: index.docker.io/danielhelfand/go-web-server@sha256:6c0b0765617ea48ab434f58dd7b3481f50539bbc31de2d8a38c67754ef232a74
        url: index.docker.io/danielhelfand/go-web-server@sha256:6c0b0765617ea48ab434f58dd7b3481f50539bbc31de2d8a38c67754ef232a74
  name: go-web-server-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-web-server
  template:
    metadata:
      labels:
        app: go-web-server
    spec:
      containers:
      - image: index.docker.io/danielhelfand/go-web-server@sha256:6c0b0765617ea48ab434f58dd7b3481f50539bbc31de2d8a38c67754ef232a74
        imagePullPolicy: Always
        name: go-web-server
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: registry-credentials
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: go-web-server
  name: go-web-server-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: go-web-server
  type: NodePort
